language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 0X6eA9rLhz/6Vatrtgn8s0UuS9OCr1+WtBMEvNExiNGq3EQwXrhfE9LZdnmqLc2fqWohWrLT6f4eVgC0T0qmmAJIDWBI3ePEsgLHI6JYNJW9edLf4cOkcedmElpvlDvvVVaBrxrB7IJ6/LtyQC+0j8RNI71yrBGsCVD3AOxHCIozGjdU1jawzX2ZiR50Z1UYPYf9AueLljky4rA51e52XraEN1cWO8ab6mENlztr2kGnQNIgPWs3x38i6Pxka1v65H7HVhBiXpkc2tGva6/mXffHyZ2dlf/+F8YvpJTnH5qKiehky31Aqe+kzwXHur/RXWHAYpAoh4D4NsS8Tec4OaGiqDWjy6k3Ut3sjPmt3df4IUiqvebnYUU6298k4CZFz/lE/Swrwu78CInPyzPYA2eiMhYpTpXXoL41jU/Gysq1fzANWQ0v59oUDqKQh45WmrrsYgOWwWQElxWZKWy8TguENvZOoJ8jRTM9VLd6bDoBNByxuwMxyzrc1tf7J+QMbRtgKX3hihvy6G+pDh3CnKLV16d7k3ha/h7DHBq+CVPHN6uF2CrPqQMXkoVHnv1tjo2kr2N2dMdMRV7SexqaC3WibRs6YhyHp6gZNvriyA8edtJKmr805dN9K4xy6VOlvP4USr8BbhKl1MD74t34sbpPkjMcIS/r8O2dQDxLg58=
  app: guarded-forest-49768
  on:
    repo: RobertVFrazier/Hot-or-Cold
